name: Windows

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

env:
  VCPKG_COMMIT: 2ad004460f5db4d3b66f62f5799ff66c265c4b5d
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        pacboy: cmake:p ninja:p make:p  # 不安装默认 GCC
        install: |
          pacman -S --needed --noconfirm mingw-w64-ucrt-x86_64-gcc=14.2.0-3
          pacman -S --needed --noconfirm cmake ninja make
    - name: Verify GCC Version
      run: gcc --version
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Configure
      run: cmake --preset=release-mingw-x86_64 -DMELONDS_EMBED_BUILD_INFO=ON
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-mingw-x86_64\melonDS.exe

