name: Windows

on:
  push:
    branches-ignore: []  # 空列表表示不忽略任何分支
  pull_request:
    branches-ignore: []  # 空列表表示不忽略任何分支

env:
  VCPKG_COMMIT: 2ad004460f5db4d3b66f62f5799ff66c265c4b5d
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
  MELONDS_VERSION_SUFFIX: " RC"

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        vmImage: [windows-2022]
    env:
      ImageVersion: "20250406.1"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
    - name: Download GCC packages
      run: |
        # download gcc 14.2
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-14.2.0-3-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-libs-14.2.0-3-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gettext-runtime-0.24-1-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-libffi-3.4.7-1-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-libuv-1.50.0-2-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-nghttp3-1.8.0-1-any.pkg.tar.zst
        curl -LO https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-openssl-3.4.1-1-any.pkg.tar.zst




        # setup gcc 14.2
        pacman -U --noconfirm \
          mingw-w64-ucrt-x86_64-gcc-libs-14.2.0-3-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-gcc-14.2.0-3-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-gettext-runtime-0.24-1-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-libffi-3.4.7-1-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-libuv-1.50.0-2-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-nghttp3-1.8.0-1-any.pkg.tar.zst \
          mingw-w64-ucrt-x86_64-openssl-3.4.1-1-any.pkg.tar.zst
          
        # setup build tools
        pacman -S --needed --noconfirm \
          mingw-w64-ucrt-x86_64-cmake \
          mingw-w64-ucrt-x86_64-ninja \
          mingw-w64-ucrt-x86_64-make

    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
    - name: Configure
      run: cmake --preset=release-mingw-x86_64 -DMELONDS_EMBED_BUILD_INFO=OFF -DUSE_QT6=OFF
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-mingw-x86_64\melonDS.exe
